"""Generate one DB2 SQL file that reloads all sample data, from data/*.csv.

The foreign keys are ON DELETE RESTRICT, so the separate gen<Table>.py
outputs with --replace only work in the right order. This script writes all
DELETEs child tables first and then all INSERTs parent tables first:

    DELETE  orders (no sample data, but it refers to stores, products and
            animals), pricesanddiscounts, inventory, animals, storesuppl,
            products, suppliers, stores, reftables
    INSERT  reftables, stores, suppliers, products, storesuppl, animals,
            inventory, pricesanddiscounts

followed by a single COMMIT. reftables has no foreign keys, but the status,
group, type and race codes of the other tables refer to it. Purchases,
customers, addresses and contactinfos are not touched.

Usage:
    python genAll.py [-e ../envs/dev1.yaml] [-o alldata.sql] [--days 30]
                     [--seed N]
"""
import argparse
import random
from datetime import datetime

import genAnimals
import genInitData
import genInventory
import genPricesAndDiscounts
import genProducts
import genRefTables
import genRelData
import genStoreSuppl
import genStores
import genSuppliers
from genInitData import (DATADIR, SCRIPTDIR, loadProfile, recentTimestamps,
                         resolve, tableName)

SCRIPT = "genAll.py"
# Parent tables first
FIRSTTABLES = [genRefTables]
CODETABLES = [genStores, genSuppliers, genProducts]
RELTABLES = [genStoreSuppl, genAnimals, genInventory, genPricesAndDiscounts]
# Child tables without sample data that must be emptied first
CLEARONLY = ["orders"]


def parseArgs():
    parser = argparse.ArgumentParser(
        prog=SCRIPT, description="Generate one SQL file that reloads all sample data")
    parser.add_argument("-e", "--env", default=SCRIPTDIR.parent / "envs" / "dev1.yaml",
                        help="environment profile (default: envs/dev1.yaml)")
    parser.add_argument("-o", "--output", help="output SQL file (default: stdout)")
    parser.add_argument("--days", type=int, default=30,
                        help="created dates lie within the last DAYS days (default: 30)")
    parser.add_argument("--seed", type=int, help="random seed, for reproducible timestamps")
    return parser.parse_args()


def codeTableLines(mod, prfl, now, days):
    table = tableName(mod.TABLENAME, prfl)
    lktables = [tableName(lk, prfl) for lk, _ in mod.LOOKUPS]
    rows = genInitData.readRows(DATADIR / f"{mod.TABLENAME}.csv",
                                mod.PREFIX, mod.EXTRAS, mod.LOOKUPS)
    lines = []
    for row in rows:
        created, updated = recentTimestamps(now, days)
        lines.append(f"-- {mod.PREFIX.capitalize()} {row[f'{mod.PREFIX}Code']}")
        lines.append(genInitData.insertStatement(table, mod.PREFIX, mod.EXTRAS, mod.LOOKUPS,
                                                 lktables, row, created, updated))
    return len(rows), lines


def main():
    args = parseArgs()
    if args.seed is not None:
        random.seed(args.seed)

    prfl = loadProfile(args.env)
    now = datetime.now()

    # Read and check everything before writing anything
    inserts, counts = [], []
    for mod in FIRSTTABLES:
        rows = genRelData.readRows(mod, DATADIR / f"{mod.TABLENAME}.csv")
        counts.append((mod.TABLENAME, len(rows)))
        inserts += [f"-- ----- {mod.TABLENAME} ({len(rows)} rows)", ""]
        inserts += genRelData.statements(mod, prfl, rows, now, args.days)
    for mod in CODETABLES:
        n, lines = codeTableLines(mod, prfl, now, args.days)
        counts.append((mod.TABLENAME, n))
        inserts += [f"-- ----- {mod.TABLENAME} ({n} rows)", ""] + lines
    for mod in RELTABLES:
        rows = genRelData.readRows(mod, DATADIR / f"{mod.TABLENAME}.csv")
        counts.append((mod.TABLENAME, len(rows)))
        inserts += [f"-- ----- {mod.TABLENAME} ({len(rows)} rows)", ""]
        inserts += genRelData.statements(mod, prfl, rows, now, args.days)

    deletes = CLEARONLY + [m.TABLENAME for m in reversed(FIRSTTABLES + CODETABLES + RELTABLES)]
    lines = ["-- Reload all petshop sample data.",
             f"-- Generated by {SCRIPT} on {now:%Y-%m-%d %H:%M:%S} from data/*.csv:",
             *[f"--   {name}: {n} rows" for name, n in counts],
             "",
             "-- Set SQLID",
             f"   SET CURRENT SQLID='{resolve('{{SQLID}}', prfl)}';",
             "",
             "-- Remove existing rows, child tables first"]
    lines += [f"   DELETE FROM {tableName(t, prfl)};" for t in deletes]
    lines += ["", "-- Insert new rows, parent tables first", ""]
    lines += inserts
    lines.append("   COMMIT;")
    genRelData.finish(lines, args.output, f"{sum(n for _, n in counts)} rows")


if __name__ == "__main__":
    main()
